config/routes.rb
Rails.application.routes.draw do
  get "search/index"
  get "like/toggle"
  get "/fandoms", to: "fandoms#index"

  devise_for :users

  resources :profiles do
    collection do
      get :filter
    end
  end

  resources :trails

  # notifications

  resources :notifications, only: [:index, :update]

  #trails
  
  resources :trails, only: [:index, :show, :new, :edit, :destroy] do
    resource :comments
    get "/by_tag/:tag", to: "trails#by_tag", on: :collection, as: "tagged"
    resources :trail_points, only: [:index, :show]
    member do
      get :purchase
      post :pay
      get :thank_you
    end
    post 'like', to: 'likes#toggle'
  end

  get 'likes/toggle/:trail_id', to: 'like#toggle', as: :toggle_like, defaults: { format: :json }

  #fandoms
  
  resources :fandoms, only: [:index, :show] do
    resource :trails do
      resources :comments, only: [:create]
    end
  end

  #purchases
  resources :purchases, only: [:index, :create]

  # admin
  
  namespace :admin do
    resources :fandoms
    resources :trails
    resources :comments
    resources :subscriptions
    resources :profiles
    resources :users
  end
  
  # api // v1

  namespace :api do
    namespace :v1 do
      resources :images, only: [:create]
      resources :trails, only: [:index, :show, :destroy] do
         patch :update_step, on: :member
         post 'purchase', on: :member
      end
      resources :likes, only: [:create]
      post 'toggle_like/:trail_id', to: 'like#toggle', as: 'toggle_like'
      resources :fandoms, only: [:index, :show]
      resources :users, only: [:index, :show, :destroy] do
        resource :profile, only: [:show, :update]
        get 'purchased_trails', on: :member
      end
      resources :profiles, only: [:index, :show, :update, :destroy]

      get "profile", to: "users#profile"

      devise_scope :user do
        post "sign_in", to: "sessions#create"
        delete "sign_out", to: "sessions#destroy", as: :destroy_user_session
        post "sign_up", to: "registrations#create"
      end
    end
  end

  get '/trails/by_tag/:tag', to: 'trails#by_tag', as: :trails_by_tag
  
  get "base_pages/index"
  get "about", to: 'base_pages#about'
  # get "community", to: 'profiles#community'
  
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get '/profiles', to: 'profiles#index'
  
  get "up" => "rails/health#show", as: :rails_health_check

  get "search", to: "search#index"
  resources :profiles, only: [:index]
  resources :fandoms, only: [:index]

  resources :notifications, only: [:index]

  # Defines the root path route ("/")
  root "base_pages#index"
end



# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
# Can be used by load balancers and uptime monitors to verify that the app is live.

app/controllers/base_pages_controller.rb
class BasePagesController < ApplicationController
  def index
    # @fandoms = Fandom.all
    # @allFandoms = [
    #     'Атлантида' , 'Шерлок' , 'Star Wars' , 'My Little Pony' ,
    #     'Доктор Кто' , 'Ван Пис' , 'Голодные игры' , '1984' ,
    #     'Игра Престолов' , 'Хроники Нарнии' , 'Звёздный десант' ,
    #     'Атака Титанов' , 'DC Comics' , 'Властелин Колец' ,
    #     'Marvel' , 'Баскетбол Куроко' , 'Мы' , 'Гарри Поттер' ,
    #     'Наруто' , 'Сумерки' , 'Клуб романтики' , 'Космическая Одиссея' ,
    #     'Однажды в сказке' , 'Великолепный век' 
    #     ]
    @random_trails = Trail.order("RANDOM()").limit(6)
    @top_trails = Trail.includes(:user).order(likes_count: :desc).limit(5)
    @marvel = Fandom.find_by(name: "Marvel")
    @marvel_trails = Trail.where(fandom_id: @marvel.id).limit(4) if @marvel

    @categories = Fandom.distinct.pluck(:category)
    @selected_category = params[:category] || @categories.first
    @fandoms = Fandom.where(category: @selected_category)
  end
    

  def about
  end
end

app/views/base_pages/about.html.erb
<body id="about">
    <div class="W_welcomeAbout">
        <div class="W_welTitle">
            <h1>путешествуй </h1>
            <h1>по следам героев</h1>
            <h1>с rutas —</h1>
            <h1>твоим проводником</h1>
            <h1>по миру фандомов</h1>
        </div>
    </div>

    <div class="W_adventure">
        <div class="W_textTitles">
            <h1>дарим приключения</h1>
            <p>На&nbsp;нашем сайте ты&nbsp;можешь выбрать свой любимый фандом и&nbsp;отправиться исследовать мир по&nbsp;уникальным маршрутам</p>
        </div>
        <div class="laptopAboutBlur">
            <div><%= image_tag '/assets/laptopAbout.png', class: 'laptopAbout' %></div>
        </div>
    </div>

    <div class="W_company">
        <div class="W_textTitles">
            <h1>помогаем найти компаньонов</h1>
            <p>В&nbsp;нашем сообществе ты&nbsp;можешь найти единомышленников и&nbsp;разделить с&nbsp;ними яркие эмоции от&nbsp;прогулок</p>
        </div>
        <div class="backBlurs"></div>
        <div class="peoples">
            <div class="firstTwo">
                <div class="M_person">
                    <%= image_tag '/assets/people/person1.jpg', class: 'chillGuy' %>
                    <div class="W_textPerson">
                        <h2>adventurer</h2>
                        <div class="W_tags">
                            <h3>владивосток</h3>
                            <h3>властелин колец</h3>
                        </div>
                    </div>
                </div>
                <div class="M_person">
                    <%= image_tag '/assets/people/person2.jpg', class: 'chillGuy' %>
                    <div class="W_textPerson">
                        <h2>elftrav</h2>
                        <div class="W_tags">
                            <h3>сочи</h3>
                            <h3>властелин колец</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="secondTwo">
                <div class="M_person">
                    <%= image_tag '/assets/people/person3.jpg', class: 'chillGuy' %>
                    <div class="W_textPerson">
                        <h2>anabelle</h2>
                        <div class="W_tags">
                            <h3>тюмень</h3>
                            <h3>сумерки</h3>
                        </div>
                    </div>
                </div>
                <div class="M_person">
                    <%= image_tag '/assets/people/person4.jpg', class: 'chillGuy' %>
                    <div class="W_textPerson">
                        <h2>notclown</h2>
                        <div class="W_tags">
                            <h3>анапа</h3>
                            <h3>сумерки</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="W_inspAbout">
        <div class="W_textTitles">
            <h1>вдохновляем делиться маршрутами</h1>
            <p>На&nbsp;нашем сайте можно выбирать места на&nbsp;карте, создавать уникальные маршруты по&nbsp;фандомам и&nbsp;делиться ими с&nbsp;другими</p>
        </div>
        <div>
            <div class="backSher"></div>
            <div class="blures">
                <div class="blur1">
                    <%= image_tag '/assets/blur1.jpg', class: 'blur' %>
                    <h1>шерлок и мистика</h1>
                </div>
                <div class="blur2">
                    <%= image_tag '/assets/blur2.jpg', class: 'blur' %>
                    <h1>призраки и тайны старых улиц</h1>
                </div>
                <div class="blur3">
                    <%= image_tag '/assets/blur3.jpg', class: 'blur' %>
                    <h1>дорогами ватсона</h1>
                </div>
                <div class="blur4">
                    <%= image_tag '/assets/blur4.jpg', class: 'blur' %>
                    <h1>на крыльях ветра и дедукции</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="W_favFandoms">
        <div class="W_textTitles">
            <h1>собираем все твои любимые фандомы</h1>
            <p>На&nbsp;нашем сайте есть множество фАНДОМОВ на&nbsp;любой вкус и&nbsp;цвет&nbsp;&mdash; выбирай&nbsp;то, что придется по&nbsp;душе именно тебе</p>
        </div>
        <div style="display: flex;">
            <div class="W_fandomAbout">
                <div class="fandom">
                    <p>(10)</p>
                    <h3>сумерки</h3>
                </div>
                <div class="fandom">
                    <p>(06)</p>
                    <h3>твин пикс</h3>
                </div>
                <div class="fandom">
                    <p>(08)</p>
                    <h3>шерлок</h3>
                </div>
                <div class="fandom">
                    <p>(14)</p>
                    <h3>звёздные войны</h3>
                </div>
                <div class="fandom">
                    <p>(09)</p>
                    <h3>дом странных детей</h3>
                </div>
                <div class="fandom">
                    <p>(12)</p>
                    <h3>властелин колец</h3>
                </div>
                <div class="fandom">
                    <p>(04)</p>
                    <h3>наруто</h3>
                </div>
            </div>
            <%= image_tag '/assets/twinPeaks.png', class: 'twinPeaks' %>
        </div>
    </div>

    <div class="W_mailer">
        <div class="W_textTitles">
            <h1>погнали вместе ходить-бродить??</h1>
            <p>Оставь здесь свой e-mail, и&nbsp;мы предупредим тебя о&nbsp;запуске rutas</p>
        </div>

        <div id="new_subscription">
            <%= render 'subscriptions/form' %>
        </div>

        <div><%= image_tag '/assets/byeBlur.png', class: 'byeBlur' %></div>

        <div class="grey"></div>
    </div>

</body>

app/views/base_pages/index.html.erb
<body id='welcome'>

  <div class="W_introduction">
    <div class="M_leftBlock">
      <div class="A_decoration"></div>
      <div class="A_mainHeading">rutas</div>
    </div>  
    <div class="M_rightBlock">
      <p class="A_textIntroduction">тут маршруты, где оживают вселенные, <br>
        и какой бы путь ты не выбрал, именно <br>
        он приведёт тебя туда, где ты и должен быть, давай ходить-бродить вместе</p>
    </div>
  </div>

  <div class="W_loopContainer">
    <div class="W_loopContent">
      <!-- Первый набор элементов -->
      <% @random_trails.each do |trail| %>
        <div class="O_trailInf">
          <%= render partial: "trails/trailProfile", locals: { trail: trail } %>
        </div>
      <% end %>

      <!-- Второй набор элементов (дубликат первого) -->
      <% @random_trails.each do |trail| %>
        <div class="O_trailInf">
          <%= render partial: "trails/trailProfile", locals: { trail: trail } %>
        </div>
      <% end %>
    </div>
  </div>

  <h2 class="A_secondHeader">Популярные маршруты</h2>
  <div class="W_topTrails">
    <div class="M_carouselItems">
      <% @top_trails.each do |trail| %>
        <div class="O_trailInf">
          <%= render partial: "trails/trailProfile", locals: { trail: trail } %>
        </div>
      <% end %>
    </div>
  </div>

  <h2 class="A_secondHeader">тебе понравится</h2>
  <div class="W_MarvelTrails">
    <div class="M_smallNaming">
      <p class="A_decorativeNaming count">(04)</p>
      <p class="A_decorativeNaming name">маршуты питера паркера</p>
    </div>
    <div class="A_backgroungMarvel"></div>
    <div class="W_marvelTrails">
      <div class="M_carouselItems marvel">
        <% if @marvel_trails.present? %>
          <% @marvel_trails.each do |trail| %>
            <div class="O_trailInf">
              <%= render partial: "trails/trailProfile", locals: { trail: trail } %>
            </div>
          <% end %>
        <% else %>
          <p>Маршрутов пока нет</p>
        <% end %>
      </div>
    </div>
  </div>

  <h2 class="A_secondHeader">ЛЮБИМЫЕ ФАНДОМЫ</h2>
  <div class="W_fandomsSections">
    <div class="W_fandomCategories">
      <% @categories.each do |cat| %>
        <%= link_to fandoms_path(category: cat), data: { turbo_frame: "fandoms_list" }, class: "M_fandomCatName #{'active' if cat == @selected_category}" do %>
          <span class="A_fandomCategoryName"><%= cat %></span>
          <span class="A_fandomCategoryCounter">(<%= Fandom.where(category: cat).count %>)</span>
        <% end %>
      <% end %>
    </div>

    <%= turbo_frame_tag "W_fandomCatShow", data: { count: 'more-than-9' } do %>
      <% @fandoms.each do |fandom| %>
        <div class="W_fandomShow" data-fandom-id="<%= fandom.id %>">
          <div class="M_fandomNameShow">
            <div class="A_fandomName">
              <% if user_signed_in? && current_user.admin? %>
                <%= link_to fandom.name, fandom_path(fandom), class: "A_fandomName" %>
              <% elsif user_signed_in? %>
                <%= link_to fandom.name, fandom_path(fandom), class: "A_fandomName" %>
              <% else %>
                <%= fandom.name %>
              <% end %>
            </div>

            <div class="A_trailCounter">
              <span class="fandom-trail-count">( <%= fandom.trails.count %> )</span>
            </div>
          </div>
          <!-- Place W_fandomTrailsShow immediately after M_fandomNameShow -->
          <div class="W_fandomTrailsShow" data-fandom-id="<%= fandom.id %>">
            <div class="M_trailColumns">
              <% fandom.trails.each do |trail| %>
                <div class="A_trailNameShow">
                  <%= link_to trail.title, trail_path(trail) %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <h2 class="A_secondHeader">Частые вопросы</h2>
  <div class="W_fag">
    <div class="M_fag">
      <p class="A_fag number">(01)</p>
      <p class="A_fag">можно ли проходить маршруты на компьютере или на ноутбуке?</p>
      <p class="A_answer">если вам удобно проходить маршруты <br> с ноутбуком в руках, то в добрый путь!</p>
    </div>
    <div class="M_fag">
      <p class="A_fag number">(02)</p>
      <p class="A_fag">маршруты только пешие или есть варианты <br> на велосипеде и транспорте?</p>
      <p class="A_answer">маршруты расчитаны на пешее прохождение, но вы можете  выбирать любой способ </p>
    </div>
    <div class="M_fag">
      <p class="A_fag number">(03)</p>
      <p class="A_fag">можно ли проходить маршруты в одиночку <br> или лучше в группе</p>
      <p class="A_answer">можно и так, и так, но в компании всегда веселее!</p>
    </div>
    <div class="M_fag">
      <p class="A_fag number">(04)</p>
      <p class="A_fag">можно ли изменять маршрут или пропускать часть пути, если устал или не успеваешь?</p>
      <p class="A_answer">да, маршруты можно корректировать под свои возможности, просто проходя их так, как вам удобно</p>
    </div>
  </div>

  <div class="A_persons"></div>

  <div class="W_mailer">
    <div class="W_textTitles">
        <h1>давай вместе ходить-бродить?</h1>
        <p>Оставь здесь свой e-mail, и мы <br>
          предупредим тебя о новосятх rutas</p>
    </div>

    <div id="new_subscription">
      <%= render 'subscriptions/form' %>
    </div>
  </div>
  </div>

</body>